spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:file:./h2
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            transaction:
            ddl-auto: update
